### ISSUE TITLE
XML output file

### ISSUE THREAD

**Issue by Hexstream** [eudoxia0/cl-ansi-spec#2]
Hello,

I can't fucking stand the CLHS anymore.

I wanted to have a quick look at the XML output file, but my infrastructure is a mess right now so generating it would be quite a hassle for me.

I was wondering if you could upload the XML output file somewhere?

**edit:** Also, the XML output file would be public domain, right?
Else it's completely useless for my purposes, heh.

**Comment by eudoxia0** [comment]
My setup is also a bit of a mess right now but I will get back to you within the week

**Comment by Hexstream** [comment]
Great! Thanks.

**Comment by eudoxia0** [comment]
[output.txt](https://github.com/LispLang/ansi-spec/files/3204187/output.txt)

**Comment by Hexstream** [comment]
Much earlier than expected, thank you!

I've had a quick look at this, right off the bat, this seems to me to be at least 10x to 20x easier to work with than the original TeX sources or a PDF rendering...

The big problem is that the "Dictionary" and "Glossary" parts seem not to be included, is this a TODO?

Other than that, the biggest annoyances that jump out at me are:

1. Although the single file can be useful for some use-cases, one file per chapter would be very useful and convenient (I could do this by hand, but it wouldn't help other users).

2. I really hate the random line wrapping, I would much prefer "one line per paragraph" instead.

3. I really hate the "double space after a sentence" convention, even though this makes no visible difference in HTML. (I'm not sure if this is safe to do as a simple search-and-replace operation).

**Comment by eudoxia0** [comment]
Yes, this parser was never complete. TeX is hell. I think someone a long time ago converted the TeX sources to Texinfo which is a more reasonable format. Maybe parsing Texinfo to generate something else might be doable.

**Comment by Hexstream** [comment]
Yes, I see. So it seems like I'll have to put this project on the backburner for now.

Thanks for the help.

**Comment by rprimus** [comment]
Wed May 22 13:14:54 BST 2019

There's:
1. https://riptutorial.com/common-lisp/example/17047/the-ansi-common-lisp-standard-in-texinfo-format--especially-useful-for-gnu-emacs-

(which also links to gcl.info).
